In [1]:
import pandas as pd
import numpy as np

In [2]:
from sqlalchemy import create_engine

In [3]:
engine = create_engine('mysql+pymysql://root:1771@localhost/us_accidents')

In [4]:
connection = engine.connect()

In [5]:
df = pd.read_csv('Clened_Dataset.csv')

In [ ]:
df

In [ ]:
df.drop(columns = 'Unnamed: 0' , inplace = True)

In [6]:
df.to_sql(
    name = 'accident',
    con = engine,
    if_exists='replace',
    chunksize=1000,
    index = False
)

7728394

In [2]:
df = pd.read_csv('Clened_Dataset.csv')

In [3]:
df.dtypes

Unnamed: 0                 int64
ID                         int64
Source                       str
Severity                   int64
Start_Time                   str
End_Time                     str
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Description                  str
Street                       str
City                         str
County                       str
State                        str
Zipcode                    int64
Country                      str
Timezone                     str
Airport_Code                 str
Weather_Timestamp            str
Temperature(F)             int64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)               int64
Visibility(mi)             int64
Wind_Direction               str
Wind_Speed(mph)          float64
Precipitation(in)        float64
Weather_Condition            str
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset               str
Civil_Twilight               str
Nautical_Twilight            str
Astronomical_Twilight        str
dtype: object

In [4]:
df2 = pd.read_csv('Ml_Ready_Dataset.csv')

🟢 Set 1 — Easy (Q1–Q7) : Data Familiarization  
Q1. What is the shape of the dataset? How many rows and columns?    
Q2. What are the column names and their data types?     
Q3. How many null/missing values are there in each column?      
Q4. What is the date range of the accidents in this dataset? (first and last accident date)     
Q5. How many unique states are covered in the dataset?      
Q6. What are the top 5 cities with the most accidents?      
Q7. What is the distribution of accident severity levels? (value counts + %)    

🟡 Set 2 — Medium (Q8–14) : Pattern Discovery   
Q8. Which hours of the day see the highest number of accidents? (accident frequency by hour)    
Q9. Is there a day-of-week pattern? Which days have the most accidents?     
Q10. What is the average distance affected (Distance(mi)) per severity level?       
Q11. Which weather conditions are most commonly associated with accidents?      
Q12. What % of accidents happen during low visibility conditions (visibility < 1 mile)?     
Q13. How has the number of accidents trended year over year?    
Q14. Which states have the highest accident rate — and does severity differ by state?       

🔴 Set 3 — Hard (Q15–20) : Deep Analysis & Inference    
Q15. Are there any strong correlations between numerical features like temperature, humidity, visibility, wind speed and severity?      
Q16. What combination of weather + time of day + road feature (junction, crossing, etc.) leads to the most severe accidents?    
Q17. Build a feature: accident duration = End_Time - Start_Time. What is the avg duration by severity and state?    
Q18. Are there geospatial hotspots? Which lat/lon clusters have disproportionately high accident density?   
Q19. Is there a statistically significant difference in severity between accidents at junctions vs non-junctions? (use a hypothesis test)   
Q20. If you had to predict accident severity — which 5 features would you select first and why, based purely on EDA?

In [5]:
# Q.1
df.shape

(7728394, 47)

In [6]:
# q2
df.dtypes

Unnamed: 0                 int64
ID                         int64
Source                       str
Severity                   int64
Start_Time                   str
End_Time                     str
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Description                  str
Street                       str
City                         str
County                       str
State                        str
Zipcode                    int64
Country                      str
Timezone                     str
Airport_Code                 str
Weather_Timestamp            str
Temperature(F)             int64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)               int64
Visibility(mi)             int64
Wind_Direction               str
Wind_Speed(mph)          float64
Precipitation(in)        float64
Weather_Condition            str
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset               str
Civil_Twilight               str
Nautical_Twilight            str
Astronomical_Twilight        str
dtype: object

In [7]:
# Q.3
df.isnull().sum()

Unnamed: 0                    0
ID                            0
Source                        0
Severity                      0
Start_Time                    0
End_Time                      0
Start_Lat                     0
Start_Lng                     0
End_Lat                       0
End_Lng                       0
Distance(mi)                  0
Description                   0
Street                        0
City                          0
County                        0
State                         0
Zipcode                       0
Country                       0
Timezone                      0
Airport_Code                  0
Weather_Timestamp             0
Temperature(F)                0
Wind_Chill(F)                 0
Humidity(%)                   0
Pressure(in)                  0
Visibility(mi)                0
Wind_Direction           113996
Wind_Speed(mph)               0
Precipitation(in)             0
Weather_Condition             0
Amenity                       0
Bump                          0
Crossing                      0
Give_Way                      0
Junction                      0
No_Exit                       0
Railway                       0
Roundabout                    0
Station                       0
Stop                          0
Traffic_Calming               0
Traffic_Signal                0
Turning_Loop                  0
Sunrise_Sunset                0
Civil_Twilight                0
Nautical_Twilight             0
Astronomical_Twilight         0
dtype: int64

In [8]:
# Q.4
df['Start_Time'] = df['Start_Time'].astype('datetime64[ns]')

In [9]:
df['Start_Time'].min()

Timestamp('2016-01-14 20:18:33')

In [10]:
df['End_Time'].max()

'2023-03-31 23:59:00'

In [11]:
# Q.5
df['State'].nunique()

49

In [12]:
# Q.6
df['City'].value_counts().head()

City
Miami          186917
Houston        169609
Los Angeles    156491
Charlotte      138652
Dallas         130939
Name: count, dtype: int64

In [13]:
# Q.7
((df['Severity'].value_counts())/df.shape[0])  * 100

Severity
2    79.667017
3    16.812510
4     2.648804
1     0.871669
Name: count, dtype: float64

In [14]:
# Q.8
df['Start_Time'].dt.hour.value_counts().head(1).index[0].item()

7

In [15]:
# Q.9
df['Start_Time'].dt.day_name().value_counts()

Start_Time
Friday       1366499
Thursday     1316229
Wednesday    1312389
Tuesday      1290929
Monday       1210921
Saturday      668683
Sunday        562744
Name: count, dtype: int64

In [16]:
# Q.10
df.groupby('Severity')['Distance(mi)'].mean()

Severity
1    0.114507
2    0.564857
3    0.423611
4    1.495756
Name: Distance(mi), dtype: float64

In [17]:
# Q.11
df['Weather_Condition'].value_counts().head(1).index.item()

'Fair'

In [18]:
df['Weather_Condition'].value_counts()

Weather_Condition
Fair                         2734261
Mostly Cloudy                1016195
Cloudy                        817082
Clear                         808743
Partly Cloudy                 698972
                              ...
Heavy Sleet / Windy                1
Sand / Windy                       1
Heavy Rain Shower / Windy          1
Blowing Snow Nearby                1
Drifting Snow                      1
Name: count, Length: 144, dtype: int64

In [19]:
# Q.12
temp_df = df[df['Visibility(mi)'] < 1]

In [20]:
temp_df.shape[0]

86989

In [21]:
(temp_df.shape[0]/df.shape[0])*100

1.125576672203824

In [22]:
# Q.13
df['Year'] = df['Start_Time'].dt.year

In [23]:
df.groupby('Year')['Start_Time'].count()

Year
2016     410821
2017     718093
2018     893426
2019     954303
2020    1178913
2021    1563753
2022    1762452
2023     246633
Name: Start_Time, dtype: int64

In [24]:
# Q.14
((df['State'].value_counts().head(10)) / df.shape[0]) * 100

State
California        22.532922
Florida           11.389067
Texas              7.541502
South Carolina     4.950019
New York           4.502358
North Carolina     4.376058
Virginia           3.924502
Pennsylvania       3.838055
Minnesota          2.485432
Oregon             2.324674
Name: count, dtype: float64

In [25]:
df.groupby(['State','Severity'])['ID'].count().reset_index()

         State  Severity     ID
0      Alabama         1    681
1      Alabama         2  76993
2      Alabama         3  21542
3      Alabama         4   1828
4      Arizona         1   7389
..         ...       ...    ...
188  Wisconsin         3   9606
189  Wisconsin         4   3462
190    Wyoming         2   3028
191    Wyoming         3    182
192    Wyoming         4    547

[193 rows x 3 columns]

In [26]:
# Q.15
df[['Distance(mi)','Temperature(F)','Humidity(%)','Pressure(in)','Visibility(mi)','Wind_Speed(mph)','Precipitation(in)']].corr(numeric_only=True)

,Distance(mi),Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
Distance(mi),1.000000,-0.052880,0.008859,-0.086512,-0.035781,0.009577,0.002032
Temperature(F),-0.052880,1.000000,-0.330367,0.126283,0.215537,0.034075,-0.005054
Humidity(%),0.008859,-0.330367,1.000000,0.113649,-0.379777,-0.172078,0.067798
Pressure(in),-0.086512,0.126283,0.113649,1.000000,0.034528,-0.024731,0.003685
Visibility(mi),-0.035781,0.215537,-0.379777,0.034528,1.000000,0.014224,-0.097759
Wind_Speed(mph),0.009577,0.034075,-0.172078,-0.024731,0.014224,1.000000,0.017774
Precipitation(in),0.002032,-0.005054,0.067798,0.003685,-0.097759,0.017774,1.000000

In [28]:
df['End_Time'] = df['End_Time'].astype('datetime64[ns]')
df['Start_Time'] = df['Start_Time'].astype('datetime64[ns]')

In [29]:
# Q.16
df['Accident _Duration'] = df['End_Time'] - df['Start_Time']

In [30]:
df['Duration(min)'] = round((df['Accident _Duration'].dt.seconds) / 60)

In [31]:
df['Duration(min)']

0          314.0
1           30.0
2           30.0
3           30.0
4           30.0
           ...
7728389     29.0
7728390     27.0
7728391     28.0
7728392     29.0
7728393     29.0
Name: Duration(min), Length: 7728394, dtype: float64

## Complaints
- q.7

## Section 2

In [32]:
df['State'].value_counts()

State
California              1741433
Florida                  880192
Texas                    582837
South Carolina           382557
New York                 347960
North Carolina           338199
Virginia                 303301
Pennsylvania             296620
Minnesota                192084
Oregon                   179660
Arizona                  170609
Georgia                  169234
Illinois                 168958
Tennessee                167388
Michigan                 162191
Louisiana                149701
New Jersey               140719
Maryland                 140417
Ohio                     118115
Washington               108221
Alabama                  101044
Utah                      97079
Colorado                  90885
Oklahoma                  83647
Missouri                  77323
Connecticut               71005
Indiana                   67224
Massachusetts             61996
Wisconsin                 34688
Kentucky                  32254
Nebraska                  28870
Montana                   28496
Iowa                      26307
Arkansas                  22780
Nevada                    21665
Kansas                    20992
District of Columbia      18630
Rhode Island              16971
Mississippi               15181
Delaware                  14097
West Virginia             13793
Idaho                     11376
New Mexico                10325
New Hampshire             10213
Wyoming                    3757
North Dakota               3487
Maine                      2698
Vermont                     926
South Dakota                289
Name: count, dtype: int64

In [33]:
df['Weather_Condition'].value_counts().head(1).index.item()

'Fair'

In [34]:
df['Sunrise_Sunset'].value_counts()

Sunrise_Sunset
Day      5357799
Night    2370595
Name: count, dtype: int64

In [35]:
df['State'].value_counts().head()

State
California        1741433
Florida            880192
Texas              582837
South Carolina     382557
New York           347960
Name: count, dtype: int64

In [36]:
df['Wind_Speed(mph)'].isna().sum().item()

0

In [37]:
df['Temperature(F)'].max().item() , df['Temperature(F)'].min().item()

(207, -89)

In [38]:
df['Visibility(mi)'].mean().item()

9.108135273641587

In [39]:
df['Year'].value_counts().sort_index()

Year
2016     410821
2017     718093
2018     893426
2019     954303
2020    1178913
2021    1563753
2022    1762452
2023     246633
Name: count, dtype: int64

In [40]:
df['Wind_Direction'].value_counts().head(1).index.item()

'CALM'

In [41]:
(((df['Severity'].value_counts())/df.shape[0]) * 100).sort_index()

Severity
1     0.871669
2    79.667017
3    16.812510
4     2.648804
Name: count, dtype: float64

In [42]:
df.groupby('Weather_Condition')['Humidity(%)'].mean().sort_values(ascending=False)

Weather_Condition
Light Fog                         100.000000
Heavy Snow with Thunder            99.000000
Partial Fog                        98.025000
Snow and Thunder                   97.857143
Thunderstorms and Snow             97.666667
                                     ...
Smoke / Windy                      19.484211
Sand / Dust Whirlwinds             14.117647
Sand / Dust Whirls Nearby          12.333333
Dust Whirls                        10.000000
Sand / Dust Whirlwinds / Windy      8.750000
Name: Humidity(%), Length: 144, dtype: float64

In [43]:
# Q.13
df[df['State']== 'Texas'].shape[0]

582837

In [44]:
# Q.14
df['Start_Time'].dt.month_name()

0          February
1          February
2          February
3          February
4          February
             ...
7728389      August
7728390      August
7728391      August
7728392      August
7728393      August
Name: Start_Time, Length: 7728394, dtype: str

In [45]:
df['Month'] = df['Start_Time'].dt.month_name()

In [46]:
df['Month'].value_counts().sort_index()

Month
April        587300
August       599666
December     847343
February     658984
January      751946
July         512335
June         571373
March        554595
May          558176
November     760165
October      675130
September    651381
Name: count, dtype: int64

In [47]:
# Q.15
df['Start_Time'].dt.day_name()

0          Monday
1          Monday
2          Monday
3          Monday
4          Monday
            ...
7728389    Friday
7728390    Friday
7728391    Friday
7728392    Friday
7728393    Friday
Name: Start_Time, Length: 7728394, dtype: str

In [48]:
df['Day_Name'] = df['Start_Time'].dt.day_name()

In [49]:
df[df['Day_Name'] == 'Sunday'].shape[0]

562744

In [50]:
# Q.16

In [51]:
df.groupby('State')['Temperature(F)'].mean()

State
Alabama                 66.454535
Arizona                 72.400712
Arkansas                59.935909
California              63.902375
Colorado                47.767541
Connecticut             54.663995
Delaware                58.969923
District of Columbia    59.609125
Florida                 75.195829
Georgia                 64.289357
Idaho                   49.362518
Illinois                52.233307
Indiana                 53.406090
Iowa                    45.249401
Kansas                  54.292064
Kentucky                58.755224
Louisiana               69.982318
Maine                   50.270571
Maryland                57.546380
Massachusetts           52.658994
Michigan                49.590101
Minnesota               38.017112
Mississippi             66.104012
Missouri                55.230940
Montana                 32.649424
Nebraska                53.982923
Nevada                  55.694300
New Hampshire           48.420445
New Jersey              57.378812
New Mexico              58.163002
New York                54.895284
North Carolina          62.862540
North Dakota            36.041583
Ohio                    52.075892
Oklahoma                63.804332
Oregon                  51.458978
Pennsylvania            53.425325
Rhode Island            55.092923
South Carolina          64.519606
South Dakota            51.096886
Tennessee               62.400160
Texas                   69.784804
Utah                    53.011970
Vermont                 45.225702
Virginia                59.512788
Washington              53.476192
West Virginia           54.227434
Wisconsin               46.845854
Wyoming                 36.105137
Name: Temperature(F), dtype: float64

In [52]:
# Q.17
df[df['Wind_Speed(mph)'] > 50].shape[0]

342

In [53]:
# Q.18
df['Start_Time'].dt.hour.value_counts().sort_values(ascending=False).head(1).index.item()

7

## Q 19 to be solved

In [54]:
# Q 20
df.groupby('Weather_Condition')['Distance(mi)'].mean()

Weather_Condition
Blowing Dust               0.527730
Blowing Dust / Windy       0.511000
Blowing Sand               1.224000
Blowing Snow               1.757559
Blowing Snow / Windy       3.139181
                             ...
Volcanic Ash               0.044545
Widespread Dust            0.291890
Widespread Dust / Windy    0.929417
Wintry Mix                 1.431755
Wintry Mix / Windy         1.054946
Name: Distance(mi), Length: 144, dtype: float64

## Q 21

In [ ]:
# Q 21

In [59]:
# Q 22
df['Traffic_Signal'].value_counts().tail(1)

Traffic_Signal
True    1143772
Name: count, dtype: int64

In [61]:
# Q 23
df['Humidity(%)'].max().item()

100.0

In [72]:
# Q 24)
df['Start_Time'][df['Start_Time'].dt.weekday.isin([5,6])].shape[0]

1231427

In [76]:
# Q 25)
df[df['Severity'] == 4]['Temperature(F)'].mean().item()

58.33077035806751

In [78]:
# Q 26)
df[df['Visibility(mi)'] == 10].shape[0]

6247355

In [ ]:
df['Visibility(mi)'].value_counts()

In [80]:
# Q27)
df['Start_Time'].dt.day.value_counts()

Start_Time
22    277077
23    276906
12    266192
14    264938
16    264611
21    264017
13    263738
15    263674
19    263066
18    262996
11    261781
20    261460
17    257276
8     253358
24    250939
1     248767
6     248515
27    248138
9     247890
7     247747
5     247612
10    247178
2     244995
3     242845
4     242592
28    240474
26    237524
25    232740
30    231731
29    225626
31    141991
Name: count, dtype: int64

In [81]:
# Q 28)
df.groupby('Severity')['Wind_Speed(mph)'].mean()

Severity
1    7.139446
2    7.529075
3    8.163044
4    7.588300
Name: Wind_Speed(mph), dtype: float64

In [84]:
# Q 29)
df[df['Month'] == 'December'].shape[0]

847343

In [86]:
# Q 30)
df['Timezone'].value_counts()

Timezone
Eastern     3580454
Pacific     2065336
Central     1650016
Mountain     432588
Name: count, dtype: int64

## Medinum

#### Q.1

In [91]:
temp_df = df[df['Severity'].isin([3,4])]['City'].value_counts().reset_index()

In [94]:
temp_df = temp_df[temp_df['count'] > 50]

In [100]:
temp_df

               City  count
0       Los Angeles  35866
1            Dallas  34223
2           Atlanta  33861
3           Houston  30521
4           Chicago  18867
...             ...    ...
2569      Leadville     51
2570        Laporte     51
2571  Stuarts Draft     51
2572         Muncie     51
2573        Molalla     51

[2574 rows x 2 columns]

In [101]:
ratio = (temp_df['count'] / df.shape[0])*100

In [103]:
temp_df['Ratio'] = ratio

In [109]:
temp_df.head(1)['City'].item()

'Los Angeles'

## Q 32 To solve

In [117]:
temp_df = df.groupby(['Year','Month'])['ID'].count().reset_index()

In [118]:
temp_df

    Year      Month      ID
0   2016      April   18088
1   2016     August   56457
2   2016   December   59619
3   2016   February     985
4   2016    January       7
..   ...        ...     ...
82  2022    October   85135
83  2022  September  139016
84  2023   February   55532
85  2023    January  160914
86  2023      March   30187

[87 rows x 3 columns]

#### Q 33)

In [126]:
avg_severity = df['Severity'].mean()

In [128]:
temp_df =  df.groupby('State')['Severity'].mean().reset_index()

In [130]:
temp_df[temp_df['Severity'] > avg_severity]

            State  Severity
0         Alabama  2.242637
2        Arkansas  2.276295
4        Colorado  2.443902
5     Connecticut  2.347032
6        Delaware  2.254309
9         Georgia  2.506931
11       Illinois  2.383302
12        Indiana  2.398072
13           Iowa  2.419432
14         Kansas  2.328077
15       Kentucky  2.454176
18       Maryland  2.332702
19  Massachusetts  2.293842
20       Michigan  2.337318
22    Mississippi  2.344312
23       Missouri  2.399609
26         Nevada  2.230879
27  New Hampshire  2.243317
28     New Jersey  2.233750
29     New Mexico  2.372107
30       New York  2.259550
33           Ohio  2.353698
37   Rhode Island  2.458252
39   South Dakota  2.442907
41          Texas  2.224124
43        Vermont  2.425486
44       Virginia  2.278974
45     Washington  2.344138
47      Wisconsin  2.473939
48        Wyoming  2.339633

#### Q 34)

In [132]:
df['Hour'] = df['Start_Time'].dt.hour

In [133]:
df.groupby(['Severity','Hour'])['ID'].count()

Severity  Hour
1         0        379
          1        259
          2        484
          3        448
          4       2642
                  ...
4         19      8906
          20      8171
          21      7748
          22      7180
          23      6654
Name: ID, Length: 96, dtype: int64